development:
  adapter: mysql2
  encoding: utf8
  database: eros39_spree_dev
  username: root
  password: ''

test: &test
  adapter: mysql2
  encoding: utf8
  database: eros39_spree_test
  username: root
  password: ''

production:
  adapter: mysql2
  encoding: utf8
  database: eros39_spree_prod
  username: root
  password: ''

cucumber:
  <<: *test
