development:
  adapter: mysql2
  encoding: utf8
  database: balticit_dev
  username: root
  password: ''

test: &test
  adapter: mysql2
  encoding: utf8
  database: balticit_test
  username: root
  password: ''

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: 62.76.178.231
  database: balticit_prod
  username: user
  password: the_password
  socket: /var/lib/mysql/mysql.sock


cucumber:
  <<: *test
